#pragma once
#include "node.h"
#include "list_node.h"
#include "number_node.h"
#include "string_node.h"

#include "argument.h"
#include "command.h"
#include "expression.h"

#include "statement.h"
#include "block_statement.h"
#include "branch_statement.h"
#include "command_statement.h"
#include "data_statement.h"
#include "embed_statement.h"
#include "header_statement.h"
#include "relocation_statement.h"
#include "constant_declaration.h"
#include "label_declaration.h"
#include "variable_declaration.h"
#include "attribute.h"